#!/bin/bash

cvmfs_test_name="Check cvmfs_config status"
cvmfs_test_suites="quick"

cvmfs_run_test() {
  logfile=$1

  cvmfs_mount sft.cern.ch || return 1
  ls /cvmfs/sft.cern.ch || return 2
  local num_status=$(cvmfs_config status | wc -l)
  if [ $num_status -lt 1 ]; then
    return 3
  fi

  cd /usr/bin || return 10
  num_status=$(cvmfs_config status | wc -l)
  if [ $num_status -lt 1 ]; then
    return 11
  fi

  if ! running_on_osx; then
    num_status=$(cvmfs_config status sft.cern.ch | wc -l)
    if [ $num_status -lt 10 ]; then
      return 20
    fi
  fi

  return 0
}

