/**
 * This file is part of the CernVM File System.
 */
#ifndef CVMFS_EXPORT_PLUGIN_FS_TRAVERSAL_POSIX_H_
#define CVMFS_EXPORT_PLUGIN_FS_TRAVERSAL_POSIX_H_

#define WARNING_FILE_NAME "DO_NOT_MODIFY_THIS_IS_AN_AUTOGENERATED_DIRECTORY"

struct fs_traversal *posix_get_interface();

#endif  // CVMFS_EXPORT_PLUGIN_FS_TRAVERSAL_POSIX_H_
