#!/bin/bash
cvmfs_test_name="Repository gateway catalog addition recursion"
cvmfs_test_autofs_on_startup=false
cvmfs_test_suites="quick"

# This test covers the maximum recursion depth of the receiver upon adding a nested catalog.
# upstream is of type GW


compare_file_checksum() {
    local file_name=$1
    local target_checksum=$2
    local checksum=$(md5sum $file_name | cut -d' ' -f1)
    echo "Checksum of $file_name is $checksum"
    if [ "$checksum" != "$target_checksum" ]; then
        echo "Checksum mismatch for $file_name. Expected $target_checksum. Found $checksum"
        return 1
    fi
}

check_recursion_depth() {
    local min_dir=$1
    local max_dir=$2
    echo "  Checking receiver recursion depth"
    syslog=$(cat_syslog | tail -n 100)
    # To guarantee finding the correct line in the syslog (and not that of a previous use of the receiver), search for the last occurrence of 'CVMFS receiver started'.
    receiver_start_string="CVMFS receiver started"
    receiver_directory="catalog diff tool entering directory"
    last_receiver_start=$(echo "$syslog" | grep -n "$receiver_start_string" | tail -n 1 | cut -d: -f1)
    if [[ -n "$last_receiver_start" ]]; then
        directories=$(echo "$syslog" | tail -n +"$last_receiver_start" | grep "$receiver_directory")
        # Check if the miniimum depth directory was entered
        if [[ "$directories" != *"'$1'"* ]]; then
            echo "  Receiver did not enter /cvmfs/test.repo.org$1"
            return 1
        fi
        # Check if the maximum depth directory was not entered
        if [[ "$directories" == *"'$2'"* ]]; then
            echo "  Receiver unnecessarily recursed into /cvmfs/test.repo.org$2 directory"
            return 2
        fi
    else
        echo "  Did not find receiver start in syslog"
        return 3
    fi

    return 0
}

check_recursion_depth() {
    local min_dir=$1
    local max_dir=$2
    echo "  Checking receiver recursion depth"
    syslog=$(cat_syslog | tail -n 100)
    # To guarantee finding the correct line in the syslog (and not that of a previous use of the receiver), search for the last occurrence of 'CVMFS receiver started'.
    receiver_start_string="CVMFS receiver started"
    receiver_directory="catalog diff tool entering directory"
    last_receiver_start=$(echo "$syslog" | grep -n "$receiver_start_string" | tail -n 1 | cut -d: -f1)
    if [[ -n "$last_receiver_start" ]]; then
        directories=$(echo "$syslog" | tail -n +"$last_receiver_start" | grep "$receiver_directory")
        # Check if the miniimum depth directory was entered
        if [[ "$directories" != *"'$1"* ]]; then
            echo "  Receiver did not enter /cvmfs/test.repo.org$1"
            return 15
        fi
        # Check if the maximum depth directory was not entered
        if [[ "$directories" == *"'$2"* ]]; then
            echo "  Receiver unnecessarily recursed into /cvmfs/test.repo.org$2 directory"
            return 16
        fi
    else
        echo "  Did not find receiver start in syslog"
        return 17
    fi
}

cvmfs_run_test() {
    set_up_repository_gateway || return 1

    echo "  Checking transaction + publish"

    ## Transaction 1
    echo "  Starting transaction 1 (Creating a deep directory tree which is assigned to nested catalogs)"
    cvmfs_server transaction test.repo.org || return 2

    echo "  Create a deep directory hierarchy"
    mkdir -p /cvmfs/test.repo.org/a || return 3
    mkdir -p /cvmfs/test.repo.org/a/b || return 4
    echo "New file" > /cvmfs/test.repo.org/a/b/c || return 5
    touch /cvmfs/test.repo.org/a/.cvmfscatalog || return 6
    touch /cvmfs/test.repo.org/a/b/.cvmfscatalog || return 7

    echo "  Publishing changes 1"
    cvmfs_server publish -v test.repo.org || return 8
    cvmfs_server check -i test.repo.org || return 9

    echo "  Checking results 1"
    compare_file_checksum /cvmfs/test.repo.org/a/b/c f1885b1a57c71cacbd923fc5e9aefef3 || return 10

    check_recursion_depth "" "/a" || return 11


    ## Transaction 2
    echo "  Starting transaction 2 (Removing highest level nested catalog)"
    cvmfs_server transaction test.repo.org || return 12

    echo "  Remove the directory containing the highest level nested catalog"
    rm -rfv /cvmfs/test.repo.org/a || return 13

    echo "  Publishing changes 2"
    cvmfs_server publish -v test.repo.org || return 14
    cvmfs_server check -i test.repo.org || return 15


    ## Transaction 3
    echo "  Starting transaction 3 (Creating a deep directory tree which is assigned to nested catalogs)"
    cvmfs_server transaction test.repo.org || return 16

    echo "  Create a deep directory hierarchy"
    mkdir -p /cvmfs/test.repo.org/a || return 17
    mkdir -p /cvmfs/test.repo.org/a/b || return 18
    mkdir -p /cvmfs/test.repo.org/a/b/c || return 19
    echo "New file" > /cvmfs/test.repo.org/a/b/c/d || return 20
    touch /cvmfs/test.repo.org/a/b/.cvmfscatalog || return 21
    touch /cvmfs/test.repo.org/a/b/c/.cvmfscatalog || return 22

    echo "  Publishing changes 3"
    cvmfs_server publish -v test.repo.org || return 23
    cvmfs_server check -i test.repo.org || return 24

    echo "  Checking results 3"
    compare_file_checksum /cvmfs/test.repo.org/a/b/c/d f1885b1a57c71cacbd923fc5e9aefef3 || return 25

    check_recursion_depth "/a" "/a/b" || return 26

    ## Transaction 4
    echo "  Starting transaction 4 (Removing the highest directory)"
    cvmfs_server transaction test.repo.org || return 26

    echo "  Remove the highest directory"
    rm -rfv /cvmfs/test.repo.org/a || return 27

    echo "  Publishing changes 4"
    cvmfs_server publish -v test.repo.org || return 28
    cvmfs_server check -i test.repo.org || return 29

    check_recursion_depth "/a" "/a/b" || return 30

    ## Transaction 5
    echo "  Starting transaction 5 (Creating a deep directory tree which is assigned to nested catalogs)"
    cvmfs_server transaction test.repo.org || return 31

    echo "  Create a deep directory hierarchy"
    mkdir -p /cvmfs/test.repo.org/a || return 32
    mkdir -p /cvmfs/test.repo.org/a/b || return 33
    echo "New file" > /cvmfs/test.repo.org/a/b/c || return 34
    touch /cvmfs/test.repo.org/a/.cvmfscatalog || return 35

    echo "  Publishing changes 5"
    cvmfs_server publish -v test.repo.org || return 37
    cvmfs_server check -i test.repo.org || return 38

    echo "  Checking results 5"
    compare_file_checksum /cvmfs/test.repo.org/a/b/c f1885b1a57c71cacbd923fc5e9aefef3 || return 39

    ## Transaction 6
    echo "  Starting transaction 6 (Manually adding a nested catalog)"
    cvmfs_server transaction test.repo.org || return 40

    echo "  Adding nested catalog in /a/b"
    touch /cvmfs/test.repo.org/a/b/.cvmfscatalog || return 41

    echo "  Publishing changes 6"
    cvmfs_server publish -v test.repo.org || return 42
    cvmfs_server check -i test.repo.org || return 43

    check_recursion_depth "" "/a" || return 44

    return 0
}
