all:
	$(MAKE) -C src all
check:
	$(MAKE) -C src check
mostlyclean:
	$(MAKE) -C src mostlyclean
clean:
	$(MAKE) -C src clean
maintainer-clean:
	$(MAKE) -C src maintainer-clean
dvi:
	$(MAKE) -C src dvi
pdf:
	$(MAKE) -C src pdf
ps:
	$(MAKE) -C src ps
info:
	$(MAKE) -C src info
html:
	$(MAKE) -C src html
tags:
	$(MAKE) -C src tags
ctags:
	$(MAKE) -C src ctags
distdir:
install: 
install-exec:
install-data:
install-dvi:
install-html:
install-info:
install-ps:
install-pdf:
installdirs:
installcheck:
uninstall:
