#!/bin/bash
cvmfs_test_name="cvmfsbundles"
cvmfs_test_autofs_on_startup=false
cvmfs_test_suites="quick"


cvmfs_run_test() {
  logfile=$1

  echo "*** Create a new repository"
  create_empty_repo $CVMFS_TEST_REPO $CVMFS_TEST_USER || return 1

  echo "*** Create and edit a bundle spec"
  start_transaction $CVMFS_TEST_REPO || return 2
  touch /cvmfs/$CVMFS_TEST_REPO/foo || return 3
  touch /cvmfs/$CVMFS_TEST_REPO/trigger || return 3
  touch /cvmfs/$CVMFS_TEST_REPO/.cvmfsbundle-trigger || return 3
  publish_repo $CVMFS_TEST_REPO || return 5

  local trigger_attr=$(get_xattr bundle_trigger /cvmfs/$CVMFS_TEST_REPO/foo)
  [ "x$trigger_attr" = x0 ] || return 11
  trigger_attr=$(get_xattr bundle_trigger /cvmfs/$CVMFS_TEST_REPO/trigger)
  [ "x$trigger_attr" = x1 ] || return 10

  start_transaction $CVMFS_TEST_REPO || return 20
  rm -f /cvmfs/$CVMFS_TEST_REPO/.cvmfsbundle-trigger || return 21
  publish_repo $CVMFS_TEST_REPO || return 22

  # TODO(jblomer): test error cases
  trigger_attr=$(get_xattr bundle_trigger /cvmfs/$CVMFS_TEST_REPO/trigger)
  [ "x$trigger_attr" = x0 ] || return 30

  return 0
}
