add_subdirectory(cmd/cvmfs_chgrp)
add_subdirectory(cmd/cvmfs_chmod)
add_subdirectory(cmd/cvmfs_chown)
add_subdirectory(cmd/cvmfs_insert)
add_subdirectory(cmd/cvmfs_ln)
add_subdirectory(cmd/cvmfs_mkdir)
add_subdirectory(cmd/cvmfs_rm)
add_subdirectory(cmd/cvmfs_rmdir)
add_subdirectory(cmd/cvmfs_rsync)
add_subdirectory(cmd/cvmfs_setfacl)
add_subdirectory(cmd/cvmfs_touch)
