#!/bin/bash

cvmfs_test_name="Change directory to config file being parsed"
cvmfs_test_suites="quick"

create_config_files() {
  sudo sh -c "echo 'echo Working-Dir-\$PWD > /tmp/cvmfs_pwd' > /etc/cvmfs/default.d/50-testcdconf.conf" || return 1

  return 0
}

cleanup_config_files() {
  sudo rm -f /etc/cvmfs/default.d/50-test*
  sudo rm -f /tmp/cvmfs_pwd
}

cvmfs_run_test() {
  logfile=$1

  local retval=0
  create_config_files || return 0
  echo "config file has /etc/cvmfs/default.d/50-testcdconf.conf"

  echo "mounting grid"
  cvmfs_mount grid.cern.ch || retval=2
  if [ $retval -eq 0 ]; then
    if [ "x$(cat /tmp/cvmfs_pwd)" != "xWorking-Dir-/etc/cvmfs/default.d" ]; then
      echo "/tmp/cvmfs_pwd has wrong content:"
      cat /tmp/cvmfs_pwd
      retval=3
    fi
  fi

  cleanup_config_files
  return $retval
}
