FROM gitlab-registry.cern.ch/cernvm/build-images/centos_x86_64:9

USER root

RUN dnf install -y sudo autofs fuse fuse3 httpd wget lsof \
    python python3-pip attr nc sqlite python3-mod_wsgi jq

RUN pip3 install flask

RUN echo '%sftnight ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

COPY test.sh test.sh

CMD ["/usr/sbin/init"]

