#!/bin/sh
cvmfs_test_name="fuse-passthru"
cvmfs_test_autofs_on_startup=false
cvmfs_test_suites=""

cleanup() {
  true
}

cvmfs_run_test() {
  this_script_dir=$TEST_ROOT/src/108-fuse-passthru
  # We want strict mode here, to catch any failure.
  # But turning on errexit (set -e) inside a function has no effect.
  # So we exec our script to keep its error handling mode independent from test/run.sh.
  exe="$this_script_dir"/run_test
  echo Launching "$exe"
  exec "$exe" "$@"
}
