#!/bin/bash

cvmfs_test_name="Check that open cache file descriptors from different processes are not duplicated in cvmfs"
cvmfs_test_suites="quick"

cleanup() {
  jobs -p | xargs kill || true
}

cvmfs_run_test() {
  logfile=$1


  ############### 1) Check that the normal cache manager 
  ############### creates new fds for the same object 
  cvmfs_mount alice.cern.ch  || return 10

  ############
  # open some test file in several simultaneously in different processes

  testfile=$(find /cvmfs/alice.cern.ch -type f | head -n1)
  # testfile has the following cvmfs hash:
  testfile_hash=$(get_xattr hash $testfile)

  for i in {1..10}; do
    tail -f ${testfile} > /dev/null 2>&1 &
  done;
  trap cleanup EXIT HUP INT TERM
  sleep 1;

  ###########
  # check the open file descriptors of the cvmfs2 process 
  alice_pid=$(cvmfs_talk -i alice.cern.ch pid)
  num_open_fds=$(ls -l /proc/$alice_pid/fd/ | grep /var/lib/cvmfs/shared/${testfile_hash:0:2}/${testfile_hash:2} | wc -l)



  if [ "$num_open_fds" -lt "2" ]; then
    echo "The normal cache manager has $num_open_fds open file descriptors for the same open test file";
    return 21
  else
    echo "The normal cache manager has $num_open_fds open file descriptors for the same open test file";
  fi

  cleanup
  sleep 1;

  cvmfs_umount alice.cern.ch || return 22

  cvmfs_mount alice.cern.ch CVMFS_CACHE_PRIMARY=posix_refcount || return 30

  ############
  # open some test file in several simultaneously in different processes

  testfile=$(find /cvmfs/alice.cern.ch -type f | head -n1)
  # testfile has the following cvmfs hash:
  testfile_hash=$(get_xattr hash $testfile)

  for i in {1..10}; do
    tail -f ${testfile} > /dev/null 2>&1 &
  done;
  trap cleanup EXIT HUP INT TERM
  sleep 1;

  ###########
  # check the open file descriptors of the cvmfs2 process 
  alice_pid=$(cvmfs_talk -i alice.cern.ch pid)
  num_open_fds=$(ls -l /proc/$alice_pid/fd/ | grep /var/lib/cvmfs/shared/${testfile_hash:0:2}/${testfile_hash:2} | wc -l)


    echo "The refcount cache manager has $num_open_fds open file descriptors for the same open test file"
  if [ "$num_open_fds" -gt "1" ]; then
    return 40
  fi

  cleanup
  return 0
}

