#!/bin/bash

cvmfs_test_name="Dummy failing test"
cvmfs_test_suites="quick dummy"

cvmfs_run_test() {
  logfile=$1

  echo "Dummy failing test"
  if [ $(get_number_of_cpu_cores) -ge 12 ]; then
    echo "source successful"
  else
    echo "source failed"
  fi

  return 1
}

