CVMFS_S3_ACCESS_KEY=**UNUSED**
CVMFS_S3_SECRET_KEY=**UNUSED**
CVMFS_S3_HOST=eg storage.googleapis.com or s3.aws.com
CVMFS_S3_PORT=80
CVMFS_S3_REGION=auto
CVMFS_S3_BUCKET=BUCKET NAME, reg test.repo
CVMFS_S3_X_AMZ_ACL=
CVMFS_S3_MAX_NUMBER_OF_PARALLEL_CONNECTIONS=100
CVMFS_S3_MAX_RETRIES=1000
CVMFS_S3_DNS_BUCKETS=false
CVMFS_S3_PEEK_BEFORE_PUT=1
CVMFS_S3_URI_SCHEME=http
CVMFS_S3_PROXY=<VARNISH PROXY URL>
