#!/bin/bash

OSXFUSE_DIR="/Library/Filesystems/osxfusefs.fs"

function display_msg()
{
  (/usr/bin/osascript) << ENDOFSCRIPT
property osxfuseurl : "https://github.com/osxfuse/osxfuse/downloads"
tell application "System Events"
  display dialog "$1" buttons {"OK", "Go to OSXFuse"} default button 1 with title "CVMFS MacOS X Installer" with icon 0
  if button returned of result is "Go to OSXFuse" then
    open location osxfuseurl
  end if
end tell
ENDOFSCRIPT
}

### check if OSXFuse is installed

if [ -d $OSXFUSE_DIR ];then
  exit 0
else
  display_msg "A OSXFuse installation is required to use cvmfs.
Please, download the latest OSXFuse version from\n
https://github.com/osxfuse/osxfuse/downloads\n
Please, follow the instructions
provided by OSXFuse to install the 
package, before you retry the installation of cvmfs." &> /dev/null  
  exit 1
fi