#!/bin/bash
cvmfs_test_name="Start image from singularity"
cvmfs_test_suites="quick"

cvmfs_run_test() {
  local logfile=$1
  local script_location=$2

  . ${script_location}/../container_common.sh

  cvmfs_mount unpacked.cern.ch,atlas.cern.ch || return 1
  apptainer exec --bind /cvmfs \
    /cvmfs/unpacked.cern.ch/registry.hub.docker.com/library/centos\:centos7 \
    mount && ls -lah /cvmfs/atlas.cern.ch && ls -lah /cvmfs/cms.cern.ch || return 10

  return 0
}
