#!/bin/bash

cvmfs_test_name="Recursive listing"

cvmfs_run_test() {
  logfile=$1

  cvmfs_mount sft.cern.ch "CVMFS_MAX_RETRIES=3" \
    "CVMFS_AUTO_UPDATE=false" \
    || return 1

  # this used to be --max-depth=3 instead of -d 3, but it had to be changed for compatibility with
  if running_on_osx; then
    sudo du -ch -d 3 /cvmfs/sft.cern.ch/lcg/releases || return 2
  else
    sudo du -ch --max-depth 3 /cvmfs/sft.cern.ch/lcg/releases || return 3
  fi
  local working_dir="$(pwd)"
  cd /cvmfs/sft.cern.ch
  purge_disk_cache
  sudo cvmfs_talk -i sft.cern.ch detach nested catalogs || return 4
  sleep 120
  check_memory sft.cern.ch 150000
  sudo cvmfs_talk -i sft.cern.ch internal affairs
  cd $working_dir

  return 0
}
