# Stage 1: Builder
FROM gitlab-registry.cern.ch/cernvm/build-images/centos_x86_64:9 AS builder

USER root

RUN yum -y install rpm-build fuse
RUN echo '%sftnight ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

ENV USER sftnight

RUN mkdir -p /home/sftnight/buildpackage
RUN mkdir -p /home/sftnight/buildpackage_config
RUN mkdir -p /home/sftnight/cvmfs

# Copy the repo
COPY . /home/sftnight/cvmfs
RUN cd /home/sftnight/cvmfs; ./ci/build_package.sh $PWD $PWD/../buildpackage/ cvmfs
RUN cd /home/sftnight/cvmfs; ./ci/build_package.sh $PWD $PWD/../buildpackage_config/ cvmfs-config

# Stage 2: Final
FROM almalinux:9

USER root

# Copy binaries from the builder stage
COPY --from=builder /home/sftnight/buildpackage/RPMS/x86_64/ /tmp/.
COPY --from=builder /home/sftnight/buildpackage_config/RPMS/noarch/ /tmp/.

RUN yum -y install /tmp/*.rpm

RUN echo '%sftnight ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

ENV USER sftnight

CMD ["/usr/sbin/init"]

