FROM gitlab-registry.cern.ch/cernvm/build-images/centos_x86_64:9

USER root


#RUN yum install -y https://cvmrepo.s3.cern.ch/cvmrepo/yum/cvmfs-release-latest.noarch.rpm
#RUN yum install -y cvmfs-2.10.1 cvmfs-server-2.10.1 cvmfs-gateway-2.10.1 


RUN echo '%sftnight ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

ENV USER sftnight

RUN yum -y install rpm-build
RUN cd /home/sftnight/cvmfs; ./ci/build_package.sh $PWD $PWD/../buildpackage/ cvmfs

CMD ["/usr/sbin/init"]

