#!/bin/bash

cvmfs_test_name="Repository reload with config repository and manual mount"
cvmfs_test_suites="quick"
cvmfs_test_autofs_on_startup=false

# Test for CVM-1755
cvmfs_run_test() {
  logfile=$1

  # Disable autofs before manual mount
  autofs_switch off || return 1

  # Make sure necessary default.local content is present before manual mount
  sudo sh -c "echo \"CVMFS_HTTP_PROXY=DIRECT\" >> /etc/cvmfs/default.local" || return 2
  sudo sh -c "echo \"CVMFS_REPOSITORIES=sft.cern.ch\" >> /etc/cvmfs/default.local" || return 3

  cvmfs_mount_direct sft.cern.ch || return 4
  mount | grep cvmfs-config.cern.ch || return 5

  cvmfs_umount cvmfs-config.cern.ch || return 6
  mount | grep cvmfs-config.cern.ch && return 7

  sudo cvmfs_config reload || return 8

  return 0
}
