#!/bin/bash

cvmfs_test_name="Check that simultaneous mount attempts only mount the repository once"
cvmfs_test_suites="quick"

cleanup() {
  echo "running cleanup()"
  sudo sed -i'' -e '/^CVMFS_HTTP_PROXY=DIRECT/d' /etc/cvmfs/default.local
  # clean up all mount attempts, a bunch of times for good measure 
  sudo umount /cvmfs/atlas-condb.cern.ch || true
  sudo umount /cvmfs/atlas-condb.cern.ch || true
  sudo umount /cvmfs/atlas-condb.cern.ch || true
  sudo umount /cvmfs/atlas-condb.cern.ch || true
  sudo umount /cvmfs/atlas-condb.cern.ch || true
  sudo umount /cvmfs/atlas-condb.cern.ch || true
  sudo umount /cvmfs/cvmfs-config.cern.ch || true

  autofs_switch on
}


cvmfs_run_test() {
  logfile=$1
  src_location=$2

  autofs_switch off

  trap cleanup EXIT HUP INT TERM || return 2


  # try to mount the same repository several times simultaneously
  # using the test function mount_cvmfs is not concurrent enough,
  # so need to mount directly
  sudo sh -c 'echo "CVMFS_HTTP_PROXY=DIRECT" >> /etc/cvmfs/default.local'
  sudo mkdir -p /cvmfs/atlas-condb.cern.ch
  sudo mkdir -p /cvmfs/cvmfs-config.cern.ch
  sudo mount -t cvmfs cvmfs-config.cern.ch /cvmfs/cvmfs-config.cern.ch
  sudo mount -t cvmfs atlas-condb.cern.ch  /cvmfs/atlas-condb.cern.ch &
  sudo mount -t cvmfs atlas-condb.cern.ch  /cvmfs/atlas-condb.cern.ch &
  sudo mount -t cvmfs atlas-condb.cern.ch  /cvmfs/atlas-condb.cern.ch &
  sudo mount -t cvmfs atlas-condb.cern.ch  /cvmfs/atlas-condb.cern.ch &
  sleep 1

  local num_cvmfs_processes=$(ps -efww | grep mount | grep atlas-condb | wc -l)

  if [ "$num_cvmfs_processes" -gt "2" ]; then
    echo "Error: more than one cvmfs process running after multiple simultaneous mounts"  
    return 21
  fi
  return 0
}

