#!/bin/sh
#
# This file is part of the CernVM File System
# This script takes care of creating, removing, and maintaining repositories
# on a Stratum 0/1 server


# Includes
#####
# The following files should be sourced in this order and before the other files
source "server/cvmfs_server_prelude.sh"
source "server/cvmfs_server_util.sh"
source "server/cvmfs_server_ssl.sh"
source "server/cvmfs_server_apache.sh"
source "server/cvmfs_server_json.sh"
source "server/cvmfs_server_common.sh"
source "server/cvmfs_server_health_check.sh"
source "server/cvmfs_server_compat.sh"
#####

# The following files contain the implementation of various subcommands. The can be sourced
# in any order
source "server/cvmfs_server_transaction.sh"
source "server/cvmfs_server_abort.sh"
source "server/cvmfs_server_publish.sh"
source "server/cvmfs_server_import.sh"
source "server/cvmfs_server_mkfs.sh"
source "server/cvmfs_server_add_replica.sh"
source "server/cvmfs_server_rmfs.sh"
source "server/cvmfs_server_resign.sh"
source "server/cvmfs_server_list_catalogs.sh"
source "server/cvmfs_server_info.sh"
source "server/cvmfs_server_tag.sh"
source "server/cvmfs_server_deprecated.sh"
source "server/cvmfs_server_check.sh"
source "server/cvmfs_server_list.sh"
source "server/cvmfs_server_rollback.sh"
source "server/cvmfs_server_gc.sh"
source "server/cvmfs_server_snapshot.sh"
source "server/cvmfs_server_migrate.sh"
source "server/cvmfs_server_chown.sh"
source "server/cvmfs_server_eliminate_hardlinks.sh"
source "server/cvmfs_server_update_info.sh"
source "server/cvmfs_server_mount.sh"
source "server/cvmfs_server_skeleton.sh"
source "server/cvmfs_server_fix_permissions.sh"
source "server/cvmfs_server_coda.sh"


