#!/bin/sh
#
# This file is part of the CernVM File System
# This script takes care of creating, removing, and maintaining repositories
# on a Stratum 0/1 server


# Includes
#####
# The following files should be sourced in this order and before the other files
source "server/cvmfs_server_prelude.sh"
source "server/cvmfs_server_util.sh"
source "server/cvmfs_server_apache.sh"
source "server/cvmfs_server_common.sh"
source "server/cvmfs_server_health_check.sh"
source "server/cvmfs_server_compat.sh"
#####

# The following files contain the implementation of various subcommands. The can be sourced
# in any order
source "server/cvmfs_server_transaction.sh"
source "server/cvmfs_server_abort.sh"
source "server/cvmfs_server_publish.sh"
source "server/cvmfs_server_coda.sh"


