#!/bin/sh
#
# This file is part of the CernVM File System
# This script takes care of creating, removing, and maintaining repositories
# on a Stratum 0 server

set -e

die() {
  echo $1 >&2
  exit 1
}

transaction_before_hook() { :; }
transaction_after_hook() { :; }
abort_before_hook() { :; }
abort_after_hook() { :; }
publish_before_hook() { :; }
publish_after_hook() { :; }


create_master_key() {
   local name=$1
   local user=$2

   master_key="/etc/cvmfs/keys/$name.masterkey"
   master_pub="/etc/cvmfs/keys/$name.pub"

   echo -n "Creating CernVM-FS master key for $name in $master_pub... "
   openssl genrsa -out $master_key 2048 > /dev/null 2>&1
   openssl rsa -in $master_key -pubout -out $master_pub > /dev/null 2>&1
   chmod 444 $master_key $master_pub
   chown $user $master_key $master_pub
   echo "done"
}


create_cert() {
   local name=$1
   local user=$2

   local key; key="/etc/cvmfs/keys/$name.key"
   local csr; csr="/etc/cvmfs/keys/$name.csr"
   local crt; crt="/etc/cvmfs/keys/$name.crt"

   # Create self-signed certificate
   echo -n "Creating self-signed certificate for $name in $crt... "
   openssl genrsa -out $key 2048 > /dev/null 2>&1
   openssl req -new -subj "/C=/ST=/L=/O=/OU=/CN=$name CernVM-FS Release Managers" -key $key -out $csr > /dev/null 2>&1
   openssl x509 -req -days 365 -in $csr -signkey $key -out $crt > /dev/null 2>&1
   rm -f $csr
   chmod 444 $key $crt
   chown $user $master_key $master_pub
   echo "done"
}


create_whitelist() {
  local name=$1
  local user=$2
  local upstream=$3
  local temp_dir=$4

  local whitelist
  local repository_dir=$(get_local_upstream $upstream)
  if [ x"$repository_dir" != x ]; then
    whitelist=${repository_dir}/.cvmfswhitelist
  else
    whitelist=${temp_dir}/whitelist
    local upload_pipe=$(get_pipe_upstream $upstream)
  fi

  echo -n "Signing 30 day whitelist with master key... "
  echo `date -u "+%Y%m%d%H%M%S"` > ${whitelist}.unsigned
  echo "E`date -u --date='next month' "+%Y%m%d%H%M%S"`" >> ${whitelist}.unsigned
  echo "N$name" >> ${whitelist}.unsigned
  openssl x509 -fingerprint -sha1 -in /etc/cvmfs/keys/${name}.crt | grep "SHA1 Fingerprint" | sed 's/SHA1 Fingerprint=//' >> ${whitelist}.unsigned

  local sha1; sha1=`openssl sha1 < ${whitelist}.unsigned | head -c40`
  echo "--" >> ${whitelist}.unsigned
  echo $sha1 >> ${whitelist}.unsigned
  echo -n $sha1 > ${whitelist}.sha1
  openssl rsautl -inkey /etc/cvmfs/keys/${name}.masterkey -sign -in ${whitelist}.sha1 -out ${whitelist}.signature
  cat ${whitelist}.unsigned ${whitelist}.signature > $whitelist
  chown $user $whitelist

  rm -f ${whitelist}.unsigned ${whitelist}.signature ${whitelist}.sha1
  echo "done"

  if [ x"$upload_pipe" != x ]; then
    echo "$whitelist, /.cvmfswhitelist" > $upload_pipe
  fi
}


get_expiry() {
  local name=$1
  local stratum0=$2

  local expires=$(curl $stratum0/.cvmfswhitelist 2>/dev/null | head -2 | tail -1 | tail -c15)
  local year=$(echo $expires | head -c4)
  local month=$(echo $expires | head -c6 | tail -c2)
  local day=$(echo $expires | head -c8 | tail -c2)
  local expires_fmt="${year}-${month}-${day}"
  local expires_num=$(date -u -d $expires_fmt +%s)

  local now=$(/bin/date -u +%s)
  local valid_time=$(( ($expires_num-$now)/(3600*24) ))
  echo "Whitelist is valid for another $valid_time days"
}


get_local_upstream() {
  local upstream=$1

  if [ x$(echo "$upstream" | cut -d: -f1) = x"local" ]; then
    echo "$(echo $upstream | cut -d: -f2)"
  else
    echo ""
  fi
}


get_pipe_upstream() {
  local upstream=$1

  if [ x$(echo "$upstream" | cut -d: -f1) = x"pipe" ]; then
    echo "$(echo $upstream | cut -d: -f2)"
  else
    echo ""
  fi
}


reload_apache() {
   echo -n "Reloading Apache... "
   /sbin/service httpd reload > /dev/null
   echo "done"
}


transaction() {
  local name=$1
  local spool_dir=$2

  [ -f ${spool_dir}/in_transaction ] && die "Already in a transaction"

  transaction_before_hook $name
  sudo mount -o remount,rw /cvmfs/$name
  touch ${spool_dir}/in_transaction
  transaction_after_hook $name
}


abort() {
  local name=$1
  local user=$2
  local spool_dir=$3

  [ -f ${spool_dir}/in_transaction ] || die "Not in a transaction"
  fuser -m /cvmfs/$name > /dev/null 2>&1 && die "Open file descriptors on $name"

  reply=n
  read -p "You are about to DISCARD ALL CHANGES OF THE CURRENT TRANSACTION!  Are you sure (y/n)? " reply
  [ x"$reply" != xy ] && return

  local user_shell="sh -c"
  [ $(whoami) != $user ] && user_shell="su $user -c"

  abort_before_hook $name
  sudo umount /cvmfs/$name
  rm -rf ${spool_dir}/tmp/*
  sudo rm -rf ${spool_dir}/scratch
  $user_shell "mkdir /var/spool/cvmfs/${name}/scratch"
  sudo mount /cvmfs/$name
  rm -f ${spool_dir}/in_transaction
  abort_after_hook $name
}


publish() {
  local name=$1
  local user=$2
  local spool_dir=$3
  local stratum0=$4
  local upstream=$5

  [ -f ${spool_dir}/in_transaction ] || die "Not in a transaction"
  fuser -m /cvmfs/$name > /dev/null 2>&1 && die "Open file descriptors on $name"

  local user_shell="sh -c"
  [ $(whoami) != $user ] && user_shell="su $user -c"
  local repository_dir=$(get_local_upstream $upstream)

  publish_before_hook $name
  sudo /bin/mount -o remount,ro /cvmfs/$name
  local base_hash=$(attr -qg root_hash ${spool_dir}/rdonly)
  local log_level=
  [ "x$CVMFS_LOG_LEVEL" != x ] && log_level="-z $CVMFS_LOG_LEVEL"

  $user_shell "cvmfs_sync -x -u /cvmfs/$name \
    -s ${spool_dir}/scratch \
    -c ${spool_dir}/rdonly \
    -t ${spool_dir}/tmp \
    -b $base_hash \
    -p ${spool_dir}/paths \
    -d ${spool_dir}/digests \
    -l $repository_dir \
    -w $stratum0 \
    -o ${spool_dir}/tmp/manifest \
    $log_level" || die "Synchronization failed"
  $user_shell "cvmfs_sign -c /etc/cvmfs/keys/${name}.crt \
    -k /etc/cvmfs/keys/${name}.key \
    -n $name \
    -m ${spool_dir}/tmp/manifest \
    -t ${spool_dir}/tmp \
    -p ${spool_dir}/paths \
    -d ${spool_dir}/digests \
    -l $repository_dir" || die "Signing failed"
  echo "Remounting newly created repository revision"
  sudo umount /cvmfs/$name
  sudo umount ${spool_dir}/rdonly
  sudo rm -rf ${spool_dir}/scratch
  rm -rf ${spool_dir}/tmp/*
  $user_shell "mkdir ${spool_dir}/scratch"
  sudo mount ${spool_dir}/rdonly > /dev/null
  sudo mount /cvmfs/$name
  rm -f ${spool_dir}/in_transaction
  publish_after_hook $name
}


create_repository_skeleton() {
  local directory=$1
  local user=$2

  echo -n "Creating repository skeleton in ${directory}..."
  mkdir -p ${directory}/data
  local i=0
  while [ $i -lt 256 ]
  do
    mkdir ${directory}/data/$(printf "%02x" $i)
    i=$(($i+1))
  done
  chown -R $user $directory
  echo "done"
}


mkfs() {
  local name=$1
  local stratum0=$2
  local upstream=$3

  local spool_dir="/var/spool/cvmfs/${name}"
  local scratch_dir="${spool_dir}/scratch"
  local rdonly_dir="${spool_dir}/rdonly"
  local temp_dir="${spool_dir}/tmp"
  local pipe_paths="${spool_dir}/paths"
  local pipe_digests="${spool_dir}/digests"
  local repository_dir=$(get_local_upstream $upstream)
  local repository_pipe=$(get_pipe_upstream $upstream)
  if [ x"$repository_pipe" = x"DEFAULT" ]; then
    repository_pipe=${spool_dir}/upload
    upstream="pipe:$repository_pipe"
  fi

  # Sanity checks
  [ $(id -u) -ne 0 ] && die "Only root can create a new repository"
  modprobe aufs || die "aufs kernel module missing"
  cat /proc/mounts | grep -q "^/etc/auto.cvmfs /cvmfs " && die "Autofs on /cvmfs has to be disabled"

  local cvmfs_user
  read -p "Owner of $name [$(whoami)]: " cvmfs_user
  [ x"$cvmfs_user" = x ] && cvmfs_user=$(whoami)
  id $cvmfs_user > /dev/null 2>&1 || die "No user $cvmfs_user"

  echo -n "Creating configuration files... "
  mkdir -p /etc/cvmfs/repositories.d/${name}
  cat > /etc/cvmfs/repositories.d/${name}/server.conf << EOF
# Created by cvmfs_server.
CVMFS_REPOSITORY_NAME=$name
CVMFS_USER=$cvmfs_user
CVMFS_UNION_DIR=/cvmfs/$name
CVMFS_SPOOL_DIR=$spool_dir
CVMFS_STRATUM0=$stratum0
CVMFS_UPSTREAM_STORAGE=$upstream
EOF
  cat > /etc/httpd/conf.d/cvmfs.${name}.conf << EOF
# Created by cvmfs_server.  Don't touch.
# For pushing files to the worker nodes
Alias /fanout/cvmfs/$name /cvmfs/$name
<Directory "/cvmfs/$name">
    Options -MultiViews
    AllowOverride All
    Order allow,deny
    Allow from all
    EnableMMAP Off
    EnableSendFile Off
</Directory>
# For pushing catalogs to upstream storage
Alias /fanout/$temp_dir $temp_dir
<Directory "$temp_dir">
    Options -MultiViews
    AllowOverride All
    Order allow,deny
    Allow from all
    EnableMMAP Off
    EnableSendFile Off
</Directory>
EOF
  if [ x"$stratum0" = x"http://localhost/cvmfs/$name" ]; then
    cat >> /etc/httpd/conf.d/cvmfs.${name}.conf << EOF
# Translation URL to real pathname
Alias /cvmfs/$name ${repository_dir}
<Directory "${repository_dir}">
    Options -MultiViews
    AllowOverride All
    Order allow,deny
    Allow from all

    EnableMMAP Off
    EnableSendFile Off

    AddType application/x-cvmfs .cvmfspublished .cvmfswhitelist

    Header unset Last-Modified
    FileETag None

    ExpiresActive On
    ExpiresDefault "access plus 3 days"
    ExpiresByType text/html "access plus 5 minutes"
    ExpiresByType application/x-cvmfs "access plus 1 minutes"
</Directory>
EOF
  fi
  cat > /etc/cvmfs/config.d/${name}.conf << EOF
# Created by cvmfs_server.  Don't touch.
CVMFS_SERVER_URL=$stratum0
CVMFS_HTTP_PROXY=DIRECT
CVMFS_PUBLIC_KEY=/etc/cvmfs/keys/${name}.pub
CVMFS_STRICT_MOUNT=no
EOF
  cat >> /etc/sudoers << EOF
$cvmfs_user localhost = NOPASSWD: /bin/mount -o remount\,ro /cvmfs/$name # added by CernVM-FS for $name
$cvmfs_user localhost = NOPASSWD: /bin/mount -o remount\,rw /cvmfs/$name # added by CernVM-FS for $name
$cvmfs_user localhost = NOPASSWD: /bin/umount /cvmfs/$name # added by CernVM-FS for $name
$cvmfs_user localhost = NOPASSWD: /bin/umount $rdonly_dir # added by CernVM-FS for $name
$cvmfs_user localhost = NOPASSWD: /bin/mount $rdonly_dir # added by CernVM-FS for $name
$cvmfs_user localhost = NOPASSWD: /bin/mount /cvmfs/$name # added by CernVM-FS for $name
$cvmfs_user localhost = NOPASSWD: /bin/rm -rf $scratch_dir # added by CernVM-FS for $name
EOF
  echo "done"

  mkdir -p /etc/cvmfs/keys
  create_master_key $name $cvmfs_user
  create_cert $name $cvmfs_user

  echo -n "Create CernVM-FS Storage... "
  mkdir -p /cvmfs/$name $scratch_dir $rdonly_dir $temp_dir
  mkfifo -m 0660 $pipe_paths $pipe_digests
  chown -R $cvmfs_user /cvmfs/$name $spool_dir
  if [ x"$repository_pipe" != x ]; then
    [ -p $repository_pipe ] || mkfifo -m 0660 $repository_pipe
    chown -R $cvmfs_user $repository_pipe
  fi
  if [ x"$repository_dir" != x ]; then
    create_repository_skeleton $repository_dir $cvmfs_user > /dev/null
  fi
  reload_apache > /dev/null
  echo "done"

  echo -n "Create Initial Repository... "
  create_whitelist $name $cvmfs_user $upstream $temp_dir > /dev/null
  su $cvmfs_user -c "cvmfs_sync -n \
    -t $temp_dir \
    -p $pipe_paths \
    -d $pipe_digests \
    -l $repository_dir \
    -o ${temp_dir}/new_manifest" > /dev/null
  su $cvmfs_user -c "cvmfs_sign -c /etc/cvmfs/keys/${name}.crt \
    -k /etc/cvmfs/keys/${name}.key \
    -n $name \
    -m ${temp_dir}/new_manifest \
    -t $temp_dir \
    -p $pipe_paths \
    -d $pipe_digests \
    -l $repository_dir" > /dev/null
  echo "done"

  echo -n "Mounting CernVM-FS Storage... "
  cat >> /etc/fstab << EOF
$name $rdonly_dir cvmfs no_reload 0 0 # added by CernVM-FS for $name
aufs_$name /cvmfs/$name aufs br=${scratch_dir}=rw:${rdonly_dir}=rr,udba=none,ro 0 0 # added by CernVM-FS for $name
EOF
  mount $rdonly_dir > /dev/null
  mount /cvmfs/$name
  echo "done"

  echo -n "Initial commit... "
  transaction $name $spool_dir > /dev/null
  echo "New CernVM-FS repository for $name" > /cvmfs/${name}/new_repository
  publish $name $cvmfs_user $spool_dir $stratum0 $upstream
  cat $rdonly_dir/new_repository

  echo "\

Install your software in /cvmfs/$name as user $cvmfs_user.
Once you're happy, publish using 'cvmfs_server publish'
For client configuration, have a look at 'cvmfs_server info'

If you go for production, backup you software signing keys in /etc/cvmfs/keys/!"
}


rmfs() {
  local name=$1
  local spool_dir=$2
  local upstream=$3

  [ $(id -u) -ne 0 ] && die "Only root can remove a repository"
  [ x"$spool_dir" = x ] && die "Spool directory undefined"
  [ x"$upstream" = x ] && die "Upstream storage undefined"

  echo -n "Unmounting CernVM-FS Area... "
  sed -i -e "/added by CernVM-FS for ${name}/d" /etc/fstab
  mount | grep -q " /cvmfs/$name " && umount /cvmfs/$name
  mount | grep -q " ${spool_dir}/rdonly " && umount ${spool_dir}/rdonly
  echo "done"

  echo -n "Removing spool area... "
  rm -rf $spool_dir /cvmfs/$name
  echo done

  local repository_dir=$(get_local_upstream $upstream)
  if [ "x"$repository_dir != x ]; then
    echo -n "Removing repository storage... "
    rm -rf $repository_dir
    echo "done"
  fi

  echo -n "Removing keys and configuration... "
  rm -f /etc/cvmfs/keys/$name.masterkey \
        /etc/cvmfs/keys/$name.pub \
        /etc/cvmfs/keys/$name.key \
        /etc/cvmfs/keys/$name.crt \
        /etc/cvmfs/config.d/${name}.conf \
        /etc/httpd/conf.d/cvmfs.${name}.conf
  sed -i -e "/added by CernVM-FS for ${name}/d" /etc/sudoers
  echo "done"

  echo -n "Stopping services... "
  reload_apache > /dev/null
  rm -rf /etc/cvmfs/repositories.d/$name
  echo "done"

  echo "CernVM-FS repository $name wiped out!"
}


info() {
  local name=$1
  local stratum0=$2

  echo "Repository name: $name"
  get_expiry $name $stratum0
  echo

  echo "\
Client configuration:
Add $name to CVMFS_REPOSITORIES in /etc/cvmfs/default.local
Create /etc/cvmfs/config.d/${name}.conf and set
  CVMFS_SERVER_URL=$stratum0
  CVMFS_PUBLIC_KEY=/etc/cvmfs/keys/${name}.pub
Copy /etc/cvmfs/keys/${name}.pub to the client"
}


list_repositories() {
  ls -1 /etc/cvmfs/repositories.d 2> /dev/null
}


usage() {
   echo "\
CernVM-FS Server Tool
Commands:
  mkfs <fully qualified name> [-w stratum0 url] [-u upstream storage]:
               Create a new repository with a given name
  skeleton <directory>:
               Create repository skeleton in directory
  rmfs:        Remove the repository
  resign:      Re-sign the 30 day whitelist
  info:        Print summary about the repository
  list:        List available repositories
  transaction: Start to edit a repository
  abort:       Abort transaction and return to the state before
  publish:     Make a new repository snapshot

Note: If multiple repositories are maintained, the repository name must follow
the command."
}


. /etc/cvmfs/config.sh
[ -f /etc/cvmfs/cvmfs_server_hooks.sh ] && . /etc/cvmfs/cvmfs_server_hooks.sh

select_fqrn() {
  local given_name="$1"
  if [ x"$given_name" != x ]; then
    # Check if exists
    given_name=$(cvmfs_mkfqrn $given_name)
    [ -d /etc/cvmfs/repositories.d/$given_name ] && echo $given_name
  else
    # Check if only one repository active
    [ $(list_repositories | wc -l) -eq 1 ] && list_repositories
  fi
  return 0
}
CVMFS_REPOSITORY_NAME=$(select_fqrn $2)


case $1 in
  mkfs)
    [ x"$CVMFS_REPOSITORY_NAME" != x ] && die "There is already an active repository $CVMFS_REPOSITORY_NAME"
    CVMFS_REPOSITORY_NAME=$(cvmfs_mkfqrn $2)
    if [ x"$CVMFS_REPOSITORY_NAME" = x ]; then
      usage
      exit 2
    fi
    # Stratum 0, upstream storage
    STRATUM0="http://localhost/cvmfs/$CVMFS_REPOSITORY_NAME"
    UPSTREM="local:/srv/cvmfs/$CVMFS_REPOSITORY_NAME"
    shift 2
    while getopts "w:u:" OPTION
    do
      case $OPTION in
        w)
          STRATUM0=$OPTARG
        ;;
        u)
          UPSTREM=$OPTARG
        ;;
        ?)
          echo "Invalid option"
          exit 1
        ;;
      esac
    done
    mkfs $CVMFS_REPOSITORY_NAME $STRATUM0 $UPSTREM
    ;;
  rmfs)
    [ x"$CVMFS_REPOSITORY_NAME" = x ] && die "Which repository?"
    reply=n
    read -p "You are about to WIPE OUT THE CERNVM-FS REPOSITORY INCLUDING SIGNING KEYS!  Are you sure (y/n)? " reply
    if [ "$reply" = "y" ]; then
      . /etc/cvmfs/repositories.d/${CVMFS_REPOSITORY_NAME}/server.conf
      rmfs $CVMFS_REPOSITORY_NAME $CVMFS_SPOOL_DIR $CVMFS_UPSTREAM_STORAGE
    fi
  ;;
  resign)
    [ x"$CVMFS_REPOSITORY_NAME" = x ] && die "Which repository?"
    . /etc/cvmfs/repositories.d/${CVMFS_REPOSITORY_NAME}/server.conf
    create_whitelist $CVMFS_REPOSITORY_NAME $CVMFS_USER $CVMFS_STRATUM0 ${CVMFS_SPOOL_DIR}/tmp
  ;;
  info)
    [ x"$CVMFS_REPOSITORY_NAME" = x ] && die "Which repository"
    . /etc/cvmfs/repositories.d/${CVMFS_REPOSITORY_NAME}/server.conf
    info $CVMFS_REPOSITORY_NAME $CVMFS_STRATUM0
  ;;
  list)
    list_repositories
  ;;
  transaction)
    [ x"$CVMFS_REPOSITORY_NAME" = x ] && die "Which repository"
    . /etc/cvmfs/repositories.d/${CVMFS_REPOSITORY_NAME}/server.conf
    transaction $CVMFS_REPOSITORY_NAME $CVMFS_SPOOL_DIR
  ;;
  abort)
    [ x"$CVMFS_REPOSITORY_NAME" = x ] && die "Which repository"
    . /etc/cvmfs/repositories.d/${CVMFS_REPOSITORY_NAME}/server.conf
    abort $CVMFS_REPOSITORY_NAME $CVMFS_USER $CVMFS_SPOOL_DIR
  ;;
  publish)
    [ x"$CVMFS_REPOSITORY_NAME" = x ] && die "Which repository"
    . /etc/cvmfs/repositories.d/${CVMFS_REPOSITORY_NAME}/server.conf
    publish $CVMFS_REPOSITORY_NAME $CVMFS_USER $CVMFS_SPOOL_DIR $CVMFS_STRATUM0 $CVMFS_UPSTREAM_STORAGE
  ;;
  skeleton)
    SKELETON_DIR=$2
    [ x"$SKELETON_DIR" = x ] && die "skeleton directory missing"
    read -p "Owner of $SKELETON_DIR [$(whoami)]: " SKELETON_USER
    [ x"$SKELETON_USER" = x ] && SKELETON_USER=$(whoami)
    id $SKELETON_USER > /dev/null 2>&1 || die "No user $SKELETON_USER"
    create_repository_skeleton $SKELETON_DIR $SKELETON_USER
  ;;
  *)
    usage
  ;;
esac
