/**
 * This file is part of the CernVM File System.
 */

#include "repository_tag.h"

#include <cctype>
#include <string>

#include "util/platform.h"
#include "util/string.h"

RepositoryTag::RepositoryTag(const std::string &name,
                             const std::string &description)
    : name_(name), description_(description), auto_tag_threshold_(0) { }

/**
 * Check if tag name is of the form "generic-*"
 */
bool RepositoryTag::HasGenericName() {
  return HasPrefix(name_, "generic-", false);
}

/**
 * True if `name` is a full auto-generated tag name: "generic-<ISO8601>" or,
 * on name clashes, "generic_<n>-<ISO8601>", e.g.
 * "generic-2024-01-01T00:00:00.000Z" (see SetGenericName() and the generic tag
 * handling in cvmfs_server_publish.sh). Matching on the bare "generic" prefix
 * alone would also catch user-created tags such as "generic-release", so the
 * remainder is additionally required to start like an ISO8601 UTC timestamp
 * (YYYY-...) and to end with 'Z'. This mirrors the regular expression used by
 * the non-gateway cleanup in filter_auto_tags().
 */
bool RepositoryTag::IsAutoGeneratedName(const std::string &name) {
  std::string rest;
  if (HasPrefix(name, "generic-", false)) {
    rest = name.substr(8);  // strlen("generic-")
  } else if (HasPrefix(name, "generic_", false)) {
    // Skip the numeric disambiguation suffix and the following '-'.
    size_t pos = 8;  // strlen("generic_")
    const size_t start = pos;
    while (pos < name.size() &&
           isdigit(static_cast<unsigned char>(name[pos]))) {
      ++pos;
    }
    if (pos == start || pos >= name.size() || name[pos] != '-') {
      return false;
    }
    rest = name.substr(pos + 1);
  } else {
    return false;
  }

  // rest must look like an ISO8601 UTC timestamp: "YYYY-...Z"
  if (rest.size() < 5 || rest[rest.size() - 1] != 'Z' || rest[4] != '-') {
    return false;
  }
  for (int j = 0; j < 4; ++j) {
    if (!isdigit(static_cast<unsigned char>(rest[j]))) {
      return false;
    }
  }
  return true;
}

/**
 * Set a generic tag name of the form "generic-YYYY-MM-DDThh:mm:ss.sssZ"
 */
void RepositoryTag::SetGenericName() {
  const uint64_t nanoseconds = platform_realtime_ns();

  // Use strftime() to format timestamp to one-second resolution
  const time_t seconds = static_cast<time_t>(nanoseconds / 1000000000);
  struct tm timestamp;
  gmtime_r(&seconds, &timestamp);
  char seconds_buffer[32];
  strftime(seconds_buffer, sizeof(seconds_buffer), "generic-%Y-%m-%dT%H:%M:%S",
           &timestamp);

  // Append milliseconds
  const unsigned offset_milliseconds = ((nanoseconds / 1000000) % 1000);
  char name_buffer[48];
  snprintf(name_buffer, sizeof(name_buffer), "%s.%03dZ", seconds_buffer,
           offset_milliseconds);

  name_ = std::string(name_buffer);
}
