#!/bin/bash
#
# Test for running CVMFS against an Azure S3 implementation
#
# In this test we create our own Azurite blob service.
# require az-cli and azurite to be installed, see install_azurite()
# keys are hard-coded dev keys in azurite, so safe to have in code

cvmfs_test_name="Import S3 backed cvmfs on Azure blob through azurite"
cvmfs_test_autofs_on_startup=false
cvmfs_test_suites="quick"

cleanup() {
  echo "*** cleaning up"
  sudo cvmfs_server rmfs -f azurite.cvmfs.io
  if [ -f azurite_pid ]; then
    sudo kill -9 $(cat azurite_pid)
  fi
}

create_azurite_config() {
  tee cvmfs_azurite.conf > /dev/null << EOF
CVMFS_S3_HOST=127.0.0.1:10000
CVMFS_S3_ACCESS_KEY=devstoreaccount1
CVMFS_S3_SECRET_KEY=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
CVMFS_S3_BUCKET=devstoreaccount1/test
CVMFS_S3_DNS_BUCKETS=false
CVMFS_S3_FLAVOR=azure
EOF
}

start_azurite() {
  echo "*** create azurite configuration"
  create_azurite_config || return 20

  echo "*** start azurite"
  azurite_command="sudo azurite --debug azurite.txt --loose --skipApiVersionCheck --location ./"
  local azurite_pid=$(run_background_service "$azurite_command")
  echo $azurite_pid > azurite_pid
  echo "*** Azurite PID is $azurite_pid"
  if [ "x$azurite_pid" = "x" ]; then
    return 10
  fi

  sleep 5

  echo "*** create the container and we make it public"
  az storage container create --name 'test' --connection-string 'DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;' --public-access blob || exit 21
}

cvmfs_run_test() {
  if ! running_on_s3; then
    echo "not running, since s3 tests are blocked"
    return 1
  fi

  trap cleanup EXIT HUP INT TERM || return $?

  echo "*** setup azurite"
  start_azurite || return 20

  echo "*** create repository"
  sudo cvmfs_server mkfs \
    -o root \
    -s cvmfs_azurite.conf \
    -w http://127.0.0.1:10000/devstoreaccount1/test  \
    azurite.cvmfs.io || return 40

  echo "*** create test content in the repository"
  sudo cvmfs_server transaction azurite.cvmfs.io || return 50
  sudo touch /cvmfs/azurite.cvmfs.io/miaomiao || return 51
  sudo cvmfs_server publish azurite.cvmfs.io || return 52

  echo "*** remove and preserve repository"
  sudo cvmfs_server rmfs -f -p azurite.cvmfs.io || return 53
  cvmfs_server list | grep azurite.cvmfs.io && return 54

  echo "*** import repository"
  sudo cvmfs_server import \
    -o root \
    -w http://127.0.0.1:10000/devstoreaccount1/test/azurite.cvmfs.io \
    -u S3,/var/spool/cvmfs/azurite.cvmfs.io/tmp,azurite.cvmfs.io@cvmfs_azurite.conf \
    -p -k /etc/cvmfs/keys/ \
    -r azurite.cvmfs.io || return 55

  echo "*** poke around the imported repository: transaction"
  sudo cvmfs_server transaction azurite.cvmfs.io || return 56
  echo "*** poke around the imported repository: touch file"
  sudo touch /cvmfs/azurite.cvmfs.io/miaomiao2 || return 57
  echo "*** poke around the imported repository: publish"
  sudo cvmfs_server publish azurite.cvmfs.io || return 58
  echo "*** poke around the imported repository: verify file"
  sudo ls -l /cvmfs/azurite.cvmfs.io/miaomiao* || return 59

  return 0
}
