name: Benchmark

on:
  push:
    branches:
      - devel
  pull_request:
    branches:
      - devel

jobs:
  snapshotter:
    name: "Snapshotter"
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install nerdctl
        run: |
          VERSION="1.7.7" 
          wget https://github.com/containerd/nerdctl/releases/download/v$VERSION/nerdctl-full-$VERSION-linux-amd64.tar.gz
          sudo tar Cxzvvf /usr/local nerdctl-full-$VERSION-linux-amd64.tar.gz
          sudo systemctl enable --now containerd
      
      - name: Install cvmfs dependencies
        run: |
          sudo apt-get -y update && sudo apt-get -y upgrade
          sudo apt-get -y install \
              autotools-dev \
              build-essential \
              make \
              cmake \
              cpio \
              debhelper \
              devscripts \
              gdb \
              gcc \
              g++ \
              git \
              golang \
              attr \
              autofs \
              libattr1-dev \
              libcap-dev \
              libffi-dev \
              libfuse-dev \
              libfuse3-dev \
              libssl-dev \
              pkg-config \
              python3-dev \
              python3-setuptools \
              ruby \
              ruby-dev \
              rubygems \
              unzip \
              uuid-dev \
              valgrind \
              zlib1g-dev
          
          sudo sed -i /etc/apt/sources.list -e 's/main$/main universe/'
          sudo apt-get -y update

          sudo apt-get -y install \
              autoconf \
              bison \
              doxygen \
              graphviz \
              gsfonts \
              flex \
              libhesiod-dev \
              libkrb5-dev \
              libldap2-dev \
              libsasl2-dev \
              libxml2-dev \
              sssd-common

          pip install setuptools

      - name: Build cvmfs
        run: |
          mkdir -p build
          cd build
          cmake .. -DBUILD_SNAPSHOTTER=ON
          make
          sudo make install

      - name: Configure cvmfs
        run: |
          sudo cvmfs_config setup
          sudo sh -c "echo "CVMFS_HTTP_PROXY=DIRECT" > /etc/cvmfs/default.local"
          sudo sh -c "echo "CVMFS_DEBUGLOG=/tmp/cvmfs.log" >> /etc/cvmfs/default.local"
          sudo cvmfs_config reload

          sudo systemctl stop autofs
          sudo mkdir -p /cvmfs/unpacked.cern.ch
          sudo mount -t cvmfs unpacked.cern.ch /cvmfs/unpacked.cern.ch

      - name: Configure cvmfs-snapshotter
        run: |
          sudo cp build/snapshotter/cvmfs_snapshotter /usr/local/bin/cvmfs_snapshotter
          sudo cp snapshotter/script/config/etc/systemd/system/cvmfs-snapshotter.service /etc/systemd/system/
          sudo mkdir -p /etc/containerd-cvmfs-grpc && sudo touch /etc/containerd-cvmfs-grpc/config.toml
          sudo tee /etc/containerd/config.toml > /dev/null <<EOL
          version = 2

          [plugins."io.containerd.grpc.v1.cri".containerd]
              snapshotter = "cvmfs-snapshotter"
              disable_snapshot_annotations = false

          [proxy_plugins]
              [proxy_plugins.cvmfs-snapshotter]
                  type = "snapshot"
                  address = "/run/containerd-cvmfs-grpc/containerd-cvmfs-grpc.sock"
          EOL

          sudo systemctl start cvmfs-snapshotter
          sudo systemctl restart containerd

          CVMFS_SOCK="/run/containerd-cvmfs-grpc/containerd-cvmfs-grpc.sock"
          if sudo test -S "$CVMFS_SOCK"; then
              echo "$CVMFS_SOCK exists."
          else
              echo "$CVMFS_SOCK does not exist."
              exit 1
          fi

      - name: Run benchmark
        run: |
          cd snapshotter/script
          python3 benchmark.py
