name: Hotpatch and migration tests

on:
  push:
      branches: ['devel', 'cvmfs*']
  pull_request:
      branches: ['devel', 'cvmfs*']
  workflow_dispatch:

jobs:
  docker:
    name: "Hotpatch/migration tests (dockerized, alma9)"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build CVMFS in Image
        run: |
          cd test/common/container
          docker compose up --build -d cvmfs-dev

      - name: Setup CVMFS
        run: |
          docker exec -u sftnight -t cvmfs-dev bash -c \
            "sudo cvmfs_config setup"

      - name: Run hotpatch/migration tests
        run: |
          docker exec -u sftnight -t cvmfs-dev bash -c \
            "cd /home/sftnight/cvmfs/test/common/container && CVMFS_TEST_PROXY=DIRECT bash test_migration.sh"

      - name: Archive logs
        if: ${{ always() }}
        run: |
          docker cp cvmfs-dev:/tmp/cvmfs-migration-test.log /tmp/cvmfs-migration-test.log || true
          docker logs cvmfs-dev > /tmp/cvmfs-migration-container.log 2>&1 || true

      - name: Upload logs as artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: CVMFS hotpatch-migration logs
          if-no-files-found: warn
          path: |
              /tmp/cvmfs-migration-test.log
              /tmp/cvmfs-migration-container.log
