name: virtme-ng CI
on:
  pull_request:
    branches: [devel]
  push:

jobs:
  vng_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y virtme-ng
      
      - name: Check for builddep package
        id: cvmfs-builddep-check
        run: |
          if [ -f "/home/runner/.cache/cvmfs-build-deps_*_all.deb" ]; then
            echo "package_exists=true" >> $GITHUB_OUTPUT
          else
            echo "package_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Generate build-dep metapackage
        if: steps.cvmfs-builddep-check.outputs.package_exists != 'true'
        run: |
          sudo apt-get -y update
          sudo apt-get install -y devscripts equivs ccache
          mk-build-deps ./packaging/debian/cvmfs/control
          mv cvmfs-build-deps_*_all.deb /home/runner/.cache

      - name: Install build dependencies
        run: |
          sudo apt-get install -y /home/runner/.cache/cvmfs-build-deps_*_all.deb

      - name: Build packages
        run: |
          export CVMFS_EXTERNALS_PREFIX=/home/runner/.cache/cvmfs_externals_install
          export CMAKE_CXX_COMPILER_LAUNCHER=ccache
          mkdir /tmp/build-ubuntu
          mkdir /tmp/build-ubuntu-config
          ./ci/build_package.sh $PWD /tmp/build-ubuntu-config cvmfs-config
          ./ci/build_package.sh $PWD /tmp/build-ubuntu cvmfs

      - name: Install packages
        run: |
          sudo apt-get -y remove "cvmfs*"
          sudo apt-get -y install /tmp/build-ubuntu*/*.deb
          sudo cvmfs_config setup

      - name: Run vng_testing
        run: |
          cd test/vng_testing
          ./run.sh

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: vng_testing-results
          path: |
            test/vng_testing/results/test_failures.log
            test/vng_testing/results/test_run.log