name: virtme-ng CI
on:
  pull_request:
    branches: [devel]
  push:

jobs:
  vng_tests:
    runs-on: ubuntu-latest
    steps:
      - id: lsb-release
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            source /etc/lsb-release
            echo "id=${DISTRIB_ID}" >> $GITHUB_OUTPUT
            echo "release=${DISTRIB_RELEASE}" >> $GITHUB_OUTPUT
            echo "codename=${DISTRIB_CODENAME}" >> $GITHUB_OUTPUT
            echo "description=${DISTRIB_DESCRIPTION}" >> $GITHUB_OUTPUT
            echo "id-release=${DISTRIB_ID}-${DISTRIB_RELEASE}" >> $GITHUB_OUTPUT
            echo "arch=$(uname -m)" >> $GITHUB_OUTPUT
          elif [ "$RUNNER_OS" == "macOS" ]; then
            echo "id-release=macOS-$(sw_vers -productVersion)" >> $GITHUB_OUTPUT
            echo "arch=$(uname -m)" >> $GITHUB_OUTPUT
          fi

      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Create cache directories
        run: |
          mkdir -p /home/runner/.cache

      - name: Restore CI cache
        uses: actions/cache/restore@v4
        id: cvmfs-ci-cache-restore
        with:
          path: /home/runner/.cache/
          key: v3-cvmfs-ci-cache-${{ steps.lsb-release.outputs.id-release }}-${{ steps.lsb-release.outputs.arch }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y virtme-ng
      
      - name: Check for builddep package
        id: cvmfs-builddep-check
        run: |
          if [ -f "/home/runner/.cache/cvmfs-build-deps_*_all.deb" ]; then
            echo "package_exists=true" >> $GITHUB_OUTPUT
          else
            echo "package_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Generate build-dep metapackage
        if: steps.cvmfs-builddep-check.outputs.package_exists != 'true'
        run: |
          sudo apt-get -y update
          sudo apt-get install -y devscripts equivs ccache apache2 libapache2-mod-wsgi-py3
          mk-build-deps ./packaging/debian/cvmfs/control
          mv cvmfs-build-deps_*_all.deb /home/runner/.cache

      - name: Install build dependencies
        run: |
          sudo apt-get install -y /home/runner/.cache/cvmfs-build-deps_*_all.deb

      - name: Build packages
        run: |
          export CVMFS_EXTERNALS_PREFIX=/home/runner/.cache/cvmfs_externals_install
          export CMAKE_CXX_COMPILER_LAUNCHER=ccache
          mkdir /tmp/build-ubuntu
          mkdir /tmp/build-ubuntu-config
          ./ci/build_package.sh $PWD /tmp/build-ubuntu-config cvmfs-config
          ./ci/build_package.sh $PWD /tmp/build-ubuntu cvmfs

      - name: Install packages
        run: |
          sudo apt-get -y remove "cvmfs*"
          sudo apt-get -y install /tmp/build-ubuntu*/*.deb
          sudo cvmfs_config setup

      - name: Run vng_testing
        run: |
          cd test/vng_testing

          export CVMFS_TESTCASES=${{ github.event.inputs.testCases || '"src/0* src/1* src/5* src/6* src/7* src/8*"' }}
          export CVMFS_TEST_SUITES=${{ github.event.inputs.testSuites || 'quick' }}
          CVMFS_TEST_PROXY=http://localhost:3128 \
          CVMFS_TEST_USER=$(whoami) \
          ./run.sh -s "${CVMFS_TEST_SUITES}"  \
                   -x ../src/095-fuser   \
                      ../src/004-davinci                              \
                      ../src/005-asetup                               \
                      ../src/007-testjobs                             \
                      ../src/024-reload-during-asetup                 \
                      ../src/056-lowspeedlimit                        \
                      ../src/084-premounted                           \
                      ../src/094-attachmount                          \
                      ../src/104-concurrent_mounts                    \
                      ../src/518-hardlinkstresstest                   \
                      ../src/593-nestedwhiteout                       \
                      ../src/600-securecvmfs                          \
                      ../src/628-pythonwrappedcvmfsserver             \
                      ../src/647-bearercvmfs                          \
                      ../src/672-publish_stats_hardlinks              \
                      ../src/673-acl                                  \
                      ../src/682-enter                                \
                      ../src/684-https_s3                             \
                      ../src/686-azureblob_s3                         \
                      ../src/687-import_s3                            \
                      ../src/692-https_azureblob_s3                   \
                      ../src/702-symlink_caching                      \
                      ../src/803-repository_gateway_large_files       \
                      ../src/811-commit-gateway                       \
                    --                                             \
                   "${CVMFS_TESTCASES}"      || exit 1

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: vng_testing-results
          path: |
            test/vng_testing/results/test_failures.log
            test/vng_testing/results/test_run.log

      - name: Save CI cache
        if: github.ref == 'refs/heads/devel' && github.event_name != 'pull_request'
        uses: actions/cache/save@v4
        id: cvmfs-ci-cache-save
        with:
          path: /home/runner/.cache/
          key: v3-cvmfs-ci-cache-${{ steps.lsb-release.outputs.id-release }}-${{ steps.lsb-release.outputs.arch }}
