name: cpp-linter
on:
  pull_request:
  push:

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Debug Diff
        shell: bash
        run: |
          git log > gitlog
          cat gitlog
          git diff -U0 HEAD HEAD~
